language: java
install: true

branches:
  only:
  - master

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

jdk:
  - oraclejdk8

script:
  ./gradlew build
